### ISSUE TITLE
rustg_read_toml_file is broken

### ISSUE THREAD

**Issue by SuperSayu** [tgstation/rust-g#111]
As far as I can tell, #98 broke rustg_read_toml_file.  We are using it in a tgstation branch, and when I happened to update rust_g, everything that depended on toml files broke.

the toml_file_to_json function in the library passes a json string containing "success" and "content" to byond, and the byond wrapper proc returns the value of "content" if it succeeds.  From what I can tell, the value of content is escaped so that it is not actually parsed by json_decode() during this process, and returned as a json-formatted string (thankfully, with escape characters removed) instead of an associative array.

My current workaround is to json_decode the content again before you return it, and that appears to be working.

Test code (in an otherwise empty test environment, with rust_g.dm and a data.toml file to test):

```
world.New()
        world.log << "Starting"
        var/list/result = rustg_read_toml_file("data.toml")
        world.log << "Read done"
        if(istext(result))
                world.log << "It's just text"
                world.log << result
                var/list/result2 = json_decode(result)
                if(istext(result2))
                        world.log << "still just text"
                else
                        world.log << "converted?!?"
```

For me, this code returns the incredulous "converted?!?" text.  The workaround is also functioning on a live server, providing the correct associative list for the data loaded from file.

**Comment by optimumtact** [comment]
way to go @tralezab

**Comment by ZeWaka** [comment]
Worked on the rest data

**Comment by SuperSayu** [comment]
Yeah about that test
```
var/test_json = @{"
{"database":{"data":[["delta","phi"]],"enabled":true,"ports":[8000,25565],"temp_targets":{"case":72,"cpu":79}}}
"}

/test/proc/check_toml_file2json()
    rustg_file_write(test_toml, "test.toml")

    var/toml_output = rustg_read_toml_file("test.toml")

    if (toml_output != test_json)
        CRASH("test:\n[test_toml]\n \nexpected:\n[test_json]\n \nrustg:\n[toml_output]")
```

```
var/test_json = @{"
{"database":{"data":[["delta","phi"]],"enabled":true,"ports":[8000,25565],"temp_targets":{"case":72,"cpu":79}}}
"}
	world.log << istext(test_json) //returns 1
```

**Comment by san7890** [comment]
I wrote about this a bit in https://github.com/tgstation/tgstation/pull/68690 but I think that what ZeWaka once termed a "dumb tramstation random error" (via https://github.com/tgstation/rust-g/pull/107#issuecomment-1193685754) may also be related to this bug, since the runtimes seem to be specifically happening on just the Modular Map Loaders. /tg/station configs these modular map loaders for Tramstation via this TOML file here: https://github.com/tgstation/tgstation/blob/master/strings/modular_maps/Tramstation.toml . I hope that the associated PR can also rectify that issue as well. It's a good thing we have CI for all maps there otherwise I'm like 95% certain it would have gotten to production and we would probably just get majorly large fuckups.

**Comment by SuperSayu** [comment]
The "bad index" runtimes on the map loader were exactly what we were seeing (leading to a Tramstation that was partly non-functional), and it was a royal pain to track down.  I had noticed that it was also not loading the word filter toml, but I wasn't sure exactly why it was breaking until I created the testbed in the OP.
